### ISSUE TITLE
Could you please add an open-source license?

### ISSUE THREAD

**Issue by ahiggins78** [kdprog/cxf-micrometer-metrics#2]
The project has no license so it cannot be used as is, please see:

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by ahiggins78** [comment]
We'd love to use this dependency as well, but we really need a license.

**Comment by trippinBilly1979** [comment]
@kdprog - Are you still there?   Would love to see a license added to this so that we may use it

**Comment by kdprog** [comment]
Hi all, sorry for late answer. The liscences added.

**Comment by ahiggins78** [comment]
Thanks @kdprog !
